server:
  port: 8080
spring:
  application:
    name: storage
  profiles:
    active: secret
  datasource:
    url: jdbc:postgresql://localhost:15433/postgres_backspark
    driverClassName: org.postgresql.Driver
    username: ${postgres_db.USERNAME}
    password: ${postgres_db.PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  file:
    name: logs/application.log
  level:
    root: info
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true